ignore("./css/mano_italiano_media_queries.css.scss")
ignore("./css/mano_italiano_sprites.css.scss")
ignore("./ruby/menuholder.html.erb")
ignore("./ruby/cartholder.html.erb")
ignore("./ruby/staffholder.html.erb")